function textMessageSettings = acqgui_txtMessageDlg(oldSettings)

if(~exist('oldSettings') || isempty(oldSettings))
    oldSettings.carrierNum = 1;
    oldSettings.carrier = 'att';
    oldSettings.phonenum = ''; 
    oldSettings.compName = '';
    oldSettings.bOnRestart = false;
    oldSettings.bOnWake = false;
    oldSettings.nWakeFiles = 5;
    oldSettings.nWakeMinutes = 3;
    oldSettings.bOnSong = false;
    oldSettings.nSongFiles = 5;
    oldSettings.nSongMinutes = 3;        
    %Transient variables
    oldSettings.bSentWakeSong = false;
    oldSettings.bSentNextSong = false;    
end

h = dialog;
movegui(h, 'onscreen');
get(h,'Position')

uicontrol(h, ...
                   'Position'   ,[20 390 200 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,'PhoneNumber xxx-xxx-xxxx :',            ...
                   'HorizontalAlignment','left' ...
                   );
               
editPhoneNumber = uicontrol(h, ...
                   'Position'   ,[20 370 100 20] , ...
                   'Style', 'edit',              ...                   
                   'String'     ,oldSettings.phonenum,            ...
                   'BackgroundColor'     ,'white',            ...  
                   'Tag'        ,'editPhoneNumber'        , ...                   
                   'HorizontalAlignment','left' ...                 
                   );               
               
uicontrol(h, ...
                   'Position'   ,[20 340 100 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,'Carrier:',            ...
                   'HorizontalAlignment','left' ...
                   );
               
               
popupCarrier = uicontrol(h, ...
                   'Position'   ,[20 320 100 20] , ...
                   'Style', 'popup',              ...                   
                   'String'     , {'att','tmobile','verizon','sprint'},            ...
                   'Value', oldSettings.carrierNum, ...
                   'BackgroundColor'     ,'white',            ...
                   'Tag'        ,'popupCarrier'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );                  
               
uicontrol(h, ...
                   'Position'   ,[20 290 500 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,'ComputerName:',            ...
                   'HorizontalAlignment','left' ...
                   );    
               
editComputerName = uicontrol(h, ...
                   'Position'   , [20 270 100 20] , ...
                   'Style', 'edit',              ...                   
                   'String'     ,oldSettings.compName,            ...
                   'BackgroundColor'     ,'white',            ... 
                   'Tag'        ,'editComputerName'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );                                         

checkboxOnRestart = uicontrol(h, ...
                   'Position'   , [20 240 300 20] , ...
                   'Style', 'checkbox',              ...                   
                   'String'     ,'Notify successful morning restart.',            ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'Value', oldSettings.bOnRestart, ...
                   'HorizontalAlignment','left' ...                 
                   );   
               
checkboxOnWake = uicontrol(h, ...
                   'Position'   , [20 210 230 20] , ...
                   'Style', 'checkbox',              ...                   
                   'String'     ,'Notify when the bird wakes and sings ',            ...
                   'Value', oldSettings.bOnWake, ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );             
               
editWakeNumFiles = uicontrol(h, ...
                   'Position'   , [250 210 40 20] , ...
                   'Style', 'edit',              ...    
                   'BackgroundColor'     ,'white',            ...
                   'String'     ,num2str(oldSettings.nWakeFiles),            ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );  
               
uicontrol(h, ...
                   'Position'   ,[290 207 50 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,' files in ',            ...
                   'HorizontalAlignment','left' ...
                   );                  
               
editWakeNumMinutes = uicontrol(h, ...
                   'Position'   , [340 210 50 20] , ...
                   'Style', 'edit',              ...
                   'BackgroundColor'     ,'white',            ...
                   'String'     ,num2str(oldSettings.nWakeMinutes),            ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );     
               
uicontrol(h, ...
                   'Position'   ,[390 207 50 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,' minutes. ',            ...
                   'HorizontalAlignment','left' ...
                   );                 

checkboxOnSong = uicontrol(h, ...
                  'Position'   , [20 180 230 20] , ...
                   'Style', 'checkbox',              ...                   
                   'String'     ,'Notify the next time the bird sings ',            ...
                   'Value', oldSettings.bOnSong, ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );             
               
editSongNumFiles = uicontrol(h, ...
                   'Position'   , [250 180 40 20] , ...
                   'Style', 'edit',              ...    
                   'BackgroundColor'     ,'white',            ...
                   'String'     ,num2str(oldSettings.nSongFiles),            ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );  
               
uicontrol(h, ...
                   'Position'   ,[290 177 50 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,' files in ',            ...
                   'HorizontalAlignment','left' ...
                   );                  
               
editSongNumMinutes = uicontrol(h, ...
                   'Position'   , [340 180 50 20] , ...
                   'Style', 'edit',              ...
                   'BackgroundColor'     ,'white',            ...
                   'String'     ,num2str(oldSettings.nSongMinutes),            ...
                   'Tag'        ,'checkboxOnRestart'        , ... 
                   'HorizontalAlignment','left' ...                 
                   );     
               
uicontrol(h, ...
                   'Position'   ,[390 177 50 20] , ...
                   'Style', 'text',              ...                   
                   'String'     ,' minutes. ',            ...
                   'HorizontalAlignment','left' ...
                   );                                
               
OKHandle=uicontrol(h, ...
                   'Position'   ,[20 5 75 30] , ...
                   'Style', 'pushbutton', ...
                   'KeyPressFcn',@doControlKeyPress , ...
                   'String'     ,'OK'        , ...
                   'Callback'   ,@doCallback , ...
                   'Tag'        ,'OK'        , ...
                   'UserData'   ,'OK'          ...
                   );
               
CancleHandle=uicontrol(h, ...
                   'Position'   ,[120 5 75 30] , ...
                   'Style', 'pushbutton', ...
                   'KeyPressFcn',@doControlKeyPress , ...
                   'String'     ,'Cancel'        , ...
                   'Callback'   ,@doCallback , ...
                   'Tag'        ,'Cancel'        , ...
                   'UserData'   ,'Cancel'          ...
                   );               
uiwait(h);

if ishandle(h)
    textMessageSettings=oldSettings;
    if strcmp(get(h,'UserData'),'OK'),
        carrierStrs = get(popupCarrier,'String');
        textMessageSettings.carrierNum = get(popupCarrier,'Value');
        textMessageSettings.carrier = carrierStrs{get(popupCarrier,'Value')};
        textMessageSettings.phonenum = get(editPhoneNumber,'String'); 
        textMessageSettings.compName = get(editComputerName,'String');
        textMessageSettings.bOnRestart = get(checkboxOnRestart,'Value');
        textMessageSettings.bOnWake = get(checkboxOnWake,'Value');
        textMessageSettings.nWakeFiles = str2num(get(editWakeNumFiles,'String'));
        textMessageSettings.nWakeMinutes = str2num(get(editWakeNumMinutes,'String'));
        textMessageSettings.bOnSong = get(checkboxOnSong,'Value');
        textMessageSettings.nSongFiles = str2num(get(editSongNumFiles,'String'));
        textMessageSettings.nSongMinutes = str2num(get(editSongNumMinutes,'String'));        
        %Transient variables
        textMessageSettings.bSentWakeSong = oldSettings.bSentWakeSong;
        textMessageSettings.bSentNextSong = false;
    end
    delete(h);
else
    textMessageSettings=oldSettings;
end

function doControlKeyPress(obj, evd) %#ok
switch(evd.Key)
 case {'return'}
  if ~strcmp(get(obj,'UserData'),'Cancel')
      set(gcbf,'UserData','OK');
      uiresume(gcbf);
  else
      delete(gcbf)
  end
 case 'escape'
  delete(gcbf)
end

function doCallback(obj, evd) %#ok
if ~strcmp(get(obj,'UserData'),'Cancel')
    set(gcbf,'UserData','OK');
    uiresume(gcbf);
else
    delete(gcbf)
end